version: '3.8'

services:

  ####################
  # 🐘 PostGIS DB
  ####################
  db:
    image: postgis/postgis:15-3.3
    container_name: postgis-db
    environment:
      POSTGRES_DB: pfe_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  ####################
  # ☕ Spring Boot – Georef Module
  ####################
  georef-service:
    build:
      context: ./georef-module
      dockerfile: Dockerfile
    container_name: georef-service
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/pfe_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

  ####################
  # ☕ Spring Boot – Drawing Module
  ####################
  drawing-service:
    build:
      context: ./drawing-module
      dockerfile: Dockerfile
    container_name: drawing-service
    ports:
      - "8082:8082"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/pfe_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

  ####################
  # 🐍 Flask + GDAL
  ####################
  gdal-service:
    build:
      context: ./gdal-backend
      dockerfile: Dockerfile
    container_name: gdal-service
    ports:
      - "5000:5000"
    depends_on:
      - db

  ####################
  # 🌍 GeoServer
  ####################
  geoserver:
    image: kartoza/geoserver
    container_name: geoserver
    ports:
      - "8080:8080"
    environment:
      - GEOSERVER_ADMIN_PASSWORD=admin
    volumes:
      - geoserver_data:/opt/geoserver/data_dir

volumes:
  pgdata:
  geoserver_data:
