name: CI/CD - Multi-module Backend

on:
  push:
    branches: [main]
  pull_request:

jobs:
  ########################
  # 🧪 Build & Test
  ########################
  build:
    name: Build and Test All Modules
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: pfe_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: temurin

      - name: Give permission to Maven Wrapper
        run: chmod +x ./mvnw

      - name: Verify Maven Wrapper
        run: ./mvnw --version

      - name: Build All Modules
        run: ./mvnw clean install -DskipTests

      - name: Run unit tests
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/pfe_db
          SPRING_DATASOURCE_USERNAME: postgres
          SPRING_DATASOURCE_PASSWORD: postgres
        run: ./mvnw test

  #######################
  # 🐳 Docker Build & Push - georef-module
  #######################
  docker-georef:
    name: Docker Build - georef-module
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image for georef-module
        run: docker build -f georef-module/Dockerfile -t ghcr.io/georef-drawing-organization/georef-service:latest .

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push Docker image for georef-module
        run: docker push ghcr.io/georef-drawing-organization/georef-service:latest

  #######################
  # 🐳 Docker Build & Push - drawing-module
  #######################
  docker-drawing:
    name: Docker Build - drawing-module
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image for drawing-module
        run: docker build -f drawing-module/Dockerfile -t ghcr.io/georef-drawing-organization/drawing-service:latest .

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push Docker image for drawing-module
        run: docker push ghcr.io/georef-drawing-organization/drawing-service:latest